/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import gastoelectrico.Conexion;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import java.sql.*;

/**
 *
 * @author Red
 */
public class cambiarC extends javax.swing.JFrame {

    String user = "",val="";

    /**
     * Creates new form cambiarC
     */
    public cambiarC() {
        initComponents();
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelBorder1 = new RSMaterialComponent.RSPanelBorder();
        rSPanelMaterialGradient1 = new RSMaterialComponent.RSPanelMaterialGradient();
        rSPanelMaterialImage1 = new RSMaterialComponent.RSPanelMaterialImage();
        jLabel6 = new javax.swing.JLabel();
        txtAC = new RSMaterialComponent.RSPasswordOne();
        jLabel7 = new javax.swing.JLabel();
        txtNC = new RSMaterialComponent.RSPasswordIconOne();
        txtCC = new RSMaterialComponent.RSPasswordIconOne();
        jLabel8 = new javax.swing.JLabel();
        BActualizarC = new RSMaterialComponent.RSButtonMaterialIconOne();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rSPanelBorder1.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelBorder1.setBgBorder(new java.awt.Color(153, 51, 0));

        rSPanelMaterialGradient1.setColorPrimario(new java.awt.Color(255, 215, 0));
        rSPanelMaterialGradient1.setColorSecundario(new java.awt.Color(204, 51, 0));

        rSPanelMaterialImage1.setBackground(new java.awt.Color(204, 51, 0));
        rSPanelMaterialImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/images/candado.png"))); // NOI18N
        rSPanelMaterialImage1.setShapePanel(rojeru_san.efectos.ValoresEnum.PANEL_FORMA.CIRCLE);

        javax.swing.GroupLayout rSPanelMaterialImage1Layout = new javax.swing.GroupLayout(rSPanelMaterialImage1);
        rSPanelMaterialImage1.setLayout(rSPanelMaterialImage1Layout);
        rSPanelMaterialImage1Layout.setHorizontalGroup(
            rSPanelMaterialImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 99, Short.MAX_VALUE)
        );
        rSPanelMaterialImage1Layout.setVerticalGroup(
            rSPanelMaterialImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout rSPanelMaterialGradient1Layout = new javax.swing.GroupLayout(rSPanelMaterialGradient1);
        rSPanelMaterialGradient1.setLayout(rSPanelMaterialGradient1Layout);
        rSPanelMaterialGradient1Layout.setHorizontalGroup(
            rSPanelMaterialGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelMaterialGradient1Layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(rSPanelMaterialImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rSPanelMaterialGradient1Layout.setVerticalGroup(
            rSPanelMaterialGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelMaterialImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Antigua contraseña:");

        txtAC.setForeground(new java.awt.Color(0, 0, 0));
        txtAC.setBorderColor(new java.awt.Color(153, 51, 0));
        txtAC.setName(""); // NOI18N
        txtAC.setPlaceholder("");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Nueva contraseña:");

        txtNC.setForeground(new java.awt.Color(0, 0, 0));
        txtNC.setBorderColor(new java.awt.Color(153, 51, 0));
        txtNC.setColorIcon(new java.awt.Color(153, 51, 0));
        txtNC.setPlaceholder("");

        txtCC.setForeground(new java.awt.Color(0, 0, 0));
        txtCC.setBorderColor(new java.awt.Color(153, 51, 0));
        txtCC.setColorIcon(new java.awt.Color(153, 51, 0));
        txtCC.setPlaceholder("");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Confirmar contraseña:");

        BActualizarC.setBackground(new java.awt.Color(255, 102, 0));
        BActualizarC.setText("Actualizar Contraseña");
        BActualizarC.setBackgroundHover(new java.awt.Color(51, 51, 255));
        BActualizarC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BActualizarC.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EDIT);
        BActualizarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActualizarCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rSPanelBorder1Layout = new javax.swing.GroupLayout(rSPanelBorder1);
        rSPanelBorder1.setLayout(rSPanelBorder1Layout);
        rSPanelBorder1Layout.setHorizontalGroup(
            rSPanelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelMaterialGradient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(rSPanelBorder1Layout.createSequentialGroup()
                .addGroup(rSPanelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rSPanelBorder1Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel6))
                    .addGroup(rSPanelBorder1Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel7))
                    .addGroup(rSPanelBorder1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(rSPanelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAC, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                            .addComponent(txtNC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(rSPanelBorder1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel8))
                    .addGroup(rSPanelBorder1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(BActualizarC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        rSPanelBorder1Layout.setVerticalGroup(
            rSPanelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelBorder1Layout.createSequentialGroup()
                .addComponent(rSPanelMaterialGradient1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(5, 5, 5)
                .addComponent(txtCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(BActualizarC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BActualizarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActualizarCActionPerformed
        // TODO add your handling code here:
        String passAC, passNC, passCC;
        passAC = txtAC.getText().trim();
        passNC = txtNC.getText().trim();
        passCC = txtCC.getText().trim();
        user = inicio_sesion.user;
        repaint();

        int aux = 0;

        if (passAC.equals("")) {
            txtAC.setBorderColor(Color.red);
            aux++;
        }
        if (passNC.equals("")) {
            txtNC.setBorderColor(Color.red);
            txtNC.setColorIcon(Color.red);
            aux++;
        }
        if (passCC.equals("")) {
            txtCC.setBorderColor(Color.red);
            txtCC.setColorIcon(Color.red);
            aux++;
        }
        
        if(!passNC.equals(passCC)){
            txtCC.setBorderColor(Color.red);
            txtCC.setColorIcon(Color.red);
            txtNC.setBorderColor(Color.red);
            txtNC.setColorIcon(Color.red);
            aux++;
        }

        try {
            Connection cn = Conexion.conectar();
            String sql = "SELECT contraseña FROM usuario WHERE arias= '" + user + "'";
            PreparedStatement pst = cn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                val = rs.getString("contraseña");
            }
            cn.close();
        } catch (SQLException e) {

            System.err.println("Error al consultar informacion" + e);
            JOptionPane.showMessageDialog(null, "Error al consultar información");
        }
        
        if(!val.equals(passAC)){
            txtAC.setBorderColor(Color.red);
            aux++;
        }

        if (aux == 0) {

            try {
                Connection cn2 = Conexion.conectar();
                String sql2 = "UPDATE usuario SET contraseña=? WHERE arias = '" + user + "'";
                PreparedStatement pst2 = cn2.prepareStatement(sql2);
                
                pst2.setString(1,passNC);
                
                pst2.executeUpdate();
                cn2.close();
                
                txtAC.setBackground(Color.green);
                txtNC.setBackground(Color.green);
                txtCC.setBackground(Color.green);
                
                JOptionPane.showMessageDialog(null, "Se ha actualizado la contraseña correctamente");
                this.dispose();

            } catch (SQLException e) {
                System.err.println("Error" + e);
                JOptionPane.showMessageDialog(null, "Error al actualizar los datos");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Datos incorrectos");
            aux=0;
        }
    }//GEN-LAST:event_BActualizarCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cambiarC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cambiarC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cambiarC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cambiarC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cambiarC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialIconOne BActualizarC;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private RSMaterialComponent.RSPanelBorder rSPanelBorder1;
    private RSMaterialComponent.RSPanelMaterialGradient rSPanelMaterialGradient1;
    private RSMaterialComponent.RSPanelMaterialImage rSPanelMaterialImage1;
    private RSMaterialComponent.RSPasswordOne txtAC;
    private RSMaterialComponent.RSPasswordIconOne txtCC;
    private RSMaterialComponent.RSPasswordIconOne txtNC;
    // End of variables declaration//GEN-END:variables
}
