/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Color;
import java.sql.*;
import gastoelectrico.Conexion;
import javax.swing.JOptionPane;

/**
 *
 * @author Red
 */
public class enviarS extends javax.swing.JFrame {

    int id;

    /**
     * Creates new form enviarS
     */
    public enviarS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelMaterial1 = new RSMaterialComponent.RSPanelMaterial();
        rSLabelTextIcon1 = new RSMaterialComponent.RSLabelTextIcon();
        correo = new RSMaterialComponent.RSTextFieldOne();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcion = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        BEnviarS = new RSMaterialComponent.RSButtonMaterialIconOne();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rSPanelMaterial1.setBackground(new java.awt.Color(255, 255, 255));

        rSLabelTextIcon1.setForeground(new java.awt.Color(0, 0, 0));
        rSLabelTextIcon1.setText("Escriba correo de la cuenta:");
        rSLabelTextIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SECURITY);

        correo.setForeground(new java.awt.Color(0, 0, 0));
        correo.setBorderColor(new java.awt.Color(0, 0, 0));
        correo.setPlaceholder("");

        descripcion.setColumns(20);
        descripcion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        descripcion.setRows(5);
        descripcion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(descripcion);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("(Opcional) Escriba una descripción: ");

        BEnviarS.setBackground(new java.awt.Color(0, 204, 0));
        BEnviarS.setText("Enviar Solicitud");
        BEnviarS.setBackgroundHover(new java.awt.Color(0, 255, 0));
        BEnviarS.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEND);
        BEnviarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEnviarSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rSPanelMaterial1Layout = new javax.swing.GroupLayout(rSPanelMaterial1);
        rSPanelMaterial1.setLayout(rSPanelMaterial1Layout);
        rSPanelMaterial1Layout.setHorizontalGroup(
            rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(rSLabelTextIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(BEnviarS, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        rSPanelMaterial1Layout.setVerticalGroup(
            rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(rSLabelTextIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BEnviarS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelMaterial1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelMaterial1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BEnviarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEnviarSActionPerformed
        // TODO add your handling code here:
        String email, soli;
        int aux = 0;

        email = correo.getText().trim();
        soli = descripcion.getText().trim();

        if (email.equals("")) {
            correo.setBackground(Color.red);
            aux++;
        }

        if (aux == 0) {
            try {
                Connection cn = Conexion.conectar();
                String sql = "SELECT id_user FROM usuario WHERE correo = '" + email + "'";
                PreparedStatement pst = cn.prepareStatement(sql);
                ResultSet rs = pst.executeQuery();

                while (rs.next()) {
                    id = rs.getInt("id_user");
                }
                cn.close();
                if (id == 0) {
                    JOptionPane.showMessageDialog(null, "Correo no encontrado en la base de datos");
                    correo.setBackground(Color.red);
                } else {
                    try {
                        Connection cn2 = Conexion.conectar();
                        String sql2 = "INSERT INTO solicitud VALUES (?,?,?)";
                        PreparedStatement pst2 = cn2.prepareStatement(sql2);

                        pst2.setInt(1, 0);
                        pst2.setInt(2, id);
                        pst2.setString(3, soli);

                        pst2.executeUpdate();
                        cn2.close();
                        
                        JOptionPane.showMessageDialog(null, "Se ha enviado la solicitud. El administrador le enviará un mensaje por correo");
                        this.dispose();
                    } catch (SQLException e) {
                        System.err.println("Error " + e);
                        JOptionPane.showMessageDialog(null, "Error al insertar datos en la base de datos");
                    }
                }

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error al consultar informacion");
                System.err.println("Error " + e);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Por favor rellenar el correo");
        }
    }//GEN-LAST:event_BEnviarSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(enviarS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(enviarS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(enviarS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(enviarS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new enviarS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialIconOne BEnviarS;
    private RSMaterialComponent.RSTextFieldOne correo;
    private javax.swing.JTextArea descripcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon1;
    private RSMaterialComponent.RSPanelMaterial rSPanelMaterial1;
    // End of variables declaration//GEN-END:variables
}
