/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import rojeru_san.complementos.RSUtilities;
import java.sql.*;
import gastoelectrico.Conexion;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Red
 */
public class inicio_sesion extends javax.swing.JFrame {

   public static String user="";
   String pass="";
   
    
    public inicio_sesion() {
         RSUtilities.setFullScreenJFrame(this);
        initComponents();
        
        setLocationRelativeTo(null);
        iniLabels();
        
    }
    
    public void iniLabels(){
        this.error_user.setText(null);
        this.error_pass.setText(null);
        this.error_datos.setText(null);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelMaterial1 = new RSMaterialComponent.RSPanelMaterial();
        rSCustomPopuMenu1 = new rojeru_san.complementos.RSCustomPopuMenu();
        rSPanelMaterialImage1 = new RSMaterialComponent.RSPanelMaterialImage();
        rSPanelMaterial2 = new RSMaterialComponent.RSPanelMaterial();
        jLabel1 = new javax.swing.JLabel();
        txtpass = new RSMaterialComponent.RSPasswordIconTwo();
        txtuser = new RSMaterialComponent.RSTextFieldIconTwo();
        error_pass = new javax.swing.JLabel();
        error_user = new javax.swing.JLabel();
        Bvolver = new RSMaterialComponent.RSButtonMaterialIconOne();
        BIngresar = new RSMaterialComponent.RSButtonMaterialIconOne();
        error_datos = new javax.swing.JLabel();
        BActualizarC = new RSMaterialComponent.RSButtonMaterialOne();
        BRegistrar1 = new RSMaterialComponent.RSButtonMaterialOne();
        rSPanelMaterialImage2 = new RSMaterialComponent.RSPanelMaterialImage();

        javax.swing.GroupLayout rSPanelMaterial1Layout = new javax.swing.GroupLayout(rSPanelMaterial1);
        rSPanelMaterial1.setLayout(rSPanelMaterial1Layout);
        rSPanelMaterial1Layout.setHorizontalGroup(
            rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );
        rSPanelMaterial1Layout.setVerticalGroup(
            rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rSPanelMaterialImage1.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelMaterialImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/images/18f5263e7b904a2cc8f7c8a74d0781c8-planeta-tierra-icono-plana-by-vexels.png"))); // NOI18N
        rSPanelMaterialImage1.setShadowBottom(false);
        rSPanelMaterialImage1.setShadowLeft(false);
        rSPanelMaterialImage1.setShadowRight(false);
        rSPanelMaterialImage1.setShadowTop(false);

        rSPanelMaterial2.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelMaterial2.setIntensity(10);
        rSPanelMaterial2.setPixels(10);
        rSPanelMaterial2.setRound(10);
        rSPanelMaterial2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Iniciar Sesión");
        rSPanelMaterial2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 320, 40));

        txtpass.setForeground(new java.awt.Color(0, 0, 0));
        txtpass.setBorderColor(new java.awt.Color(0, 0, 0));
        txtpass.setColorIcon(new java.awt.Color(0, 0, 0));
        txtpass.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtpass.setPhColor(new java.awt.Color(0, 0, 0));
        txtpass.setPlaceholder("Contraseña");
        txtpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassActionPerformed(evt);
            }
        });
        rSPanelMaterial2.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 330, -1));

        txtuser.setForeground(new java.awt.Color(0, 0, 0));
        txtuser.setBorderColor(new java.awt.Color(0, 0, 0));
        txtuser.setColorIcon(new java.awt.Color(0, 0, 0));
        txtuser.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtuser.setPhColor(new java.awt.Color(0, 0, 0));
        txtuser.setPlaceholder("Nick de usuario");
        rSPanelMaterial2.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 330, -1));

        error_pass.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        error_pass.setForeground(new java.awt.Color(204, 0, 0));
        error_pass.setText("*Este campo es requerido");
        rSPanelMaterial2.add(error_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        error_user.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        error_user.setForeground(new java.awt.Color(204, 0, 0));
        error_user.setText("*Este campo es requerido");
        rSPanelMaterial2.add(error_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        Bvolver.setBackground(new java.awt.Color(255, 51, 51));
        Bvolver.setText("Cerrar");
        Bvolver.setBackgroundHover(new java.awt.Color(255, 102, 0));
        Bvolver.setDoubleBuffered(true);
        Bvolver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bvolver.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.BACKSPACE);
        Bvolver.setInheritsPopupMenu(true);
        Bvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BvolverActionPerformed(evt);
            }
        });
        rSPanelMaterial2.add(Bvolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 130, -1));

        BIngresar.setBackground(new java.awt.Color(51, 102, 255));
        BIngresar.setText("Ingresar");
        BIngresar.setBackgroundHover(new java.awt.Color(102, 255, 255));
        BIngresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BIngresar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DONE);
        BIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BIngresarActionPerformed(evt);
            }
        });
        rSPanelMaterial2.add(BIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 130, -1));

        error_datos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        error_datos.setForeground(new java.awt.Color(255, 0, 0));
        error_datos.setText("Datos incorrectos");
        rSPanelMaterial2.add(error_datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        BActualizarC.setBackground(new java.awt.Color(255, 255, 255));
        BActualizarC.setForeground(new java.awt.Color(51, 51, 255));
        BActualizarC.setText("¿Has perdido la cuenta?");
        BActualizarC.setBackgroundHover(new java.awt.Color(255, 255, 255));
        BActualizarC.setForegroundHover(new java.awt.Color(51, 51, 255));
        BActualizarC.setForegroundText(new java.awt.Color(51, 51, 255));
        BActualizarC.setRippleColor(new java.awt.Color(51, 51, 255));
        BActualizarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActualizarCActionPerformed(evt);
            }
        });
        rSPanelMaterial2.add(BActualizarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 280, 20));

        BRegistrar1.setBackground(new java.awt.Color(255, 255, 255));
        BRegistrar1.setForeground(new java.awt.Color(51, 51, 255));
        BRegistrar1.setText("¿No te has registrado? Registrate ahora");
        BRegistrar1.setBackgroundHover(new java.awt.Color(255, 255, 255));
        BRegistrar1.setForegroundHover(new java.awt.Color(51, 51, 255));
        BRegistrar1.setForegroundText(new java.awt.Color(51, 51, 255));
        BRegistrar1.setRippleColor(new java.awt.Color(51, 51, 255));
        BRegistrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRegistrar1ActionPerformed(evt);
            }
        });
        rSPanelMaterial2.add(BRegistrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 280, 20));

        rSPanelMaterialImage2.setBackground(new java.awt.Color(0, 0, 0));
        rSPanelMaterialImage2.setImagen(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        rSPanelMaterialImage2.setShapePanel(rojeru_san.efectos.ValoresEnum.PANEL_FORMA.CIRCLE);

        javax.swing.GroupLayout rSPanelMaterialImage2Layout = new javax.swing.GroupLayout(rSPanelMaterialImage2);
        rSPanelMaterialImage2.setLayout(rSPanelMaterialImage2Layout);
        rSPanelMaterialImage2Layout.setHorizontalGroup(
            rSPanelMaterialImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        rSPanelMaterialImage2Layout.setVerticalGroup(
            rSPanelMaterialImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        rSPanelMaterial2.add(rSPanelMaterialImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 130, 130));

        javax.swing.GroupLayout rSPanelMaterialImage1Layout = new javax.swing.GroupLayout(rSPanelMaterialImage1);
        rSPanelMaterialImage1.setLayout(rSPanelMaterialImage1Layout);
        rSPanelMaterialImage1Layout.setHorizontalGroup(
            rSPanelMaterialImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelMaterial2, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
        );
        rSPanelMaterialImage1Layout.setVerticalGroup(
            rSPanelMaterialImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelMaterial2, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelMaterialImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelMaterialImage1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassActionPerformed

    private void BIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BIngresarActionPerformed
        
        user = txtuser.getText().trim();
        pass = txtpass.getText().trim();
        
        if(!user.equals("") ||!pass.equals("") ){
            try {
                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement("SELECT rol FROM usuario WHERE arias = '" + user
                        + "' AND contraseña = '" + pass + "'");
                
                ResultSet rs = pst.executeQuery();
                if(rs.next()){
                    
                    String rol = rs.getString("rol");
                    if(rol.equalsIgnoreCase("Administrador")){
                        dispose();
                        new inicioA().setVisible(true);
                    }else if(rol.equalsIgnoreCase("Usuario")){
                        dispose();
                        new inicioU().setVisible(true);
                    }
                }else{
                    this.error_datos.setText("Datos incorrectos");
                    txtuser.setText("");
                    txtpass.setText("");
                }
                
            } catch (SQLException e) {
                System.err.println("Error al acceder" + e);
                JOptionPane.showMessageDialog(null, "Error al iniciar sesión, por favor conectarse al administrador");
            }
         
        }else{
            this.error_user.setText("*Este campo es requerido");
            this.error_pass.setText("*Este campo es requerido");  
        }
    }//GEN-LAST:event_BIngresarActionPerformed

    private void BvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BvolverActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BvolverActionPerformed

    private void BActualizarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActualizarCActionPerformed
        // TODO add your handling code here
        new enviarS().setVisible(true);
    }//GEN-LAST:event_BActualizarCActionPerformed

    private void BRegistrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRegistrar1ActionPerformed
        // TODO add your handling code here:
        
        new registrar().setVisible(true);
    }//GEN-LAST:event_BRegistrar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio_sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio_sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio_sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio_sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio_sesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialOne BActualizarC;
    private RSMaterialComponent.RSButtonMaterialIconOne BIngresar;
    private RSMaterialComponent.RSButtonMaterialOne BRegistrar1;
    private RSMaterialComponent.RSButtonMaterialIconOne Bvolver;
    private javax.swing.JLabel error_datos;
    private javax.swing.JLabel error_pass;
    private javax.swing.JLabel error_user;
    private javax.swing.JLabel jLabel1;
    private rojeru_san.complementos.RSCustomPopuMenu rSCustomPopuMenu1;
    private RSMaterialComponent.RSPanelMaterial rSPanelMaterial1;
    private RSMaterialComponent.RSPanelMaterial rSPanelMaterial2;
    private RSMaterialComponent.RSPanelMaterialImage rSPanelMaterialImage1;
    private RSMaterialComponent.RSPanelMaterialImage rSPanelMaterialImage2;
    private RSMaterialComponent.RSPasswordIconTwo txtpass;
    private RSMaterialComponent.RSTextFieldIconTwo txtuser;
    // End of variables declaration//GEN-END:variables
}
