/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import gastoelectrico.Conexion;
import paneles.CambiarPanel;
import rojeru_san.complementos.RSUtilities;
import java.sql.*;

/**
 *
 * @author Red
 */
public class inicioU extends javax.swing.JFrame {

    String user = "", nombreU;

    /**
     * Creates new form inicioU
     */
    public inicioU() {
        RSUtilities.setFullScreenJFrame(this);
        initComponents();
        setLocationRelativeTo(null);
        this.BInicio.setSelected(true);
        new CambiarPanel(pnlSlider, new paneles.inicio());
        user = inicio_sesion.user;

        try {
            Connection cn = Conexion.conectar();

            String sql = "SELECT user_name FROM usuario WHERE arias = '" + user + "'";

            PreparedStatement pst = cn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                nombreU = rs.getString("user_name");
                JNombreU.setText("¡Welcome " + nombreU + "!");
            }

            cn.close();
        } catch (SQLException e) {
            System.err.println("Error" + e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCentro = new javax.swing.JPanel();
        rSPanelMaterial1 = new RSMaterialComponent.RSPanelMaterial();
        rSLabelTextIcon1 = new RSMaterialComponent.RSLabelTextIcon();
        rSButtonIconTwo1 = new RSMaterialComponent.RSButtonIconTwo();
        rSPanelMaterial2 = new RSMaterialComponent.RSPanelMaterial();
        BInicio = new RSMaterialComponent.RSButtonMaterialIconOne();
        rSPanelBorderImage1 = new RSMaterialComponent.RSPanelBorderImage();
        JNombreU = new javax.swing.JLabel();
        BEstadistica = new RSMaterialComponent.RSButtonMaterialIconOne();
        BArtefactos1 = new RSMaterialComponent.RSButtonMaterialIconOne();
        BAjustes = new RSMaterialComponent.RSButtonMaterialIconOne();
        BFacturas = new RSMaterialComponent.RSButtonMaterialIconOne();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlSlider = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlCentro.setBackground(new java.awt.Color(255, 255, 255));
        pnlCentro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        rSPanelMaterial1.setBackground(new java.awt.Color(255, 102, 0));
        rSPanelMaterial1.setShadowBottom(false);

        rSLabelTextIcon1.setForeground(new java.awt.Color(255, 255, 255));
        rSLabelTextIcon1.setText("PROJECT GREEN LIGHT");
        rSLabelTextIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PHONELINK);

        rSButtonIconTwo1.setBackground(new java.awt.Color(255, 102, 0));
        rSButtonIconTwo1.setToolTipText("Cerrar sesión");
        rSButtonIconTwo1.setBackgroundHover(new java.awt.Color(255, 0, 0));
        rSButtonIconTwo1.setFocusCycleRoot(true);
        rSButtonIconTwo1.setFocusPainted(false);
        rSButtonIconTwo1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.POWER_SETTINGS_NEW);
        rSButtonIconTwo1.setPreferredSize(new java.awt.Dimension(42, 42));
        rSButtonIconTwo1.setSizeIcon(40.0F);
        rSButtonIconTwo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconTwo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rSPanelMaterial1Layout = new javax.swing.GroupLayout(rSPanelMaterial1);
        rSPanelMaterial1.setLayout(rSPanelMaterial1Layout);
        rSPanelMaterial1Layout.setHorizontalGroup(
            rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSLabelTextIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 627, Short.MAX_VALUE)
                .addComponent(rSButtonIconTwo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        rSPanelMaterial1Layout.setVerticalGroup(
            rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelMaterial1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSButtonIconTwo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSLabelTextIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        rSPanelMaterial2.setBackground(new java.awt.Color(239, 238, 244));
        rSPanelMaterial2.setShadowBottom(false);
        rSPanelMaterial2.setShadowLeft(false);
        rSPanelMaterial2.setShadowTop(false);

        BInicio.setBackground(new java.awt.Color(204, 204, 204));
        BInicio.setForeground(new java.awt.Color(0, 0, 0));
        BInicio.setText("Inicio");
        BInicio.setBackgroundHover(new java.awt.Color(255, 102, 0));
        BInicio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BInicio.setForegroundIconHover(new java.awt.Color(51, 51, 51));
        BInicio.setForegroundText(new java.awt.Color(51, 51, 51));
        BInicio.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.HOME);
        BInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BInicioActionPerformed(evt);
            }
        });

        rSPanelBorderImage1.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelBorderImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/images/iconoUser.png"))); // NOI18N
        rSPanelBorderImage1.setShapePanel(rojeru_san.efectos.ValoresEnum.PANEL_FORMA.CIRCLE);

        javax.swing.GroupLayout rSPanelBorderImage1Layout = new javax.swing.GroupLayout(rSPanelBorderImage1);
        rSPanelBorderImage1.setLayout(rSPanelBorderImage1Layout);
        rSPanelBorderImage1Layout.setHorizontalGroup(
            rSPanelBorderImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 104, Short.MAX_VALUE)
        );
        rSPanelBorderImage1Layout.setVerticalGroup(
            rSPanelBorderImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        JNombreU.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        JNombreU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JNombreU.setText("Nombre Usuario");

        BEstadistica.setBackground(new java.awt.Color(204, 204, 204));
        BEstadistica.setForeground(new java.awt.Color(0, 0, 0));
        BEstadistica.setText("Estadisticas");
        BEstadistica.setBackgroundHover(new java.awt.Color(255, 102, 0));
        BEstadistica.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BEstadistica.setForegroundIconHover(new java.awt.Color(51, 51, 51));
        BEstadistica.setForegroundText(new java.awt.Color(51, 51, 51));
        BEstadistica.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.INFO_OUTLINE);
        BEstadistica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEstadisticaActionPerformed(evt);
            }
        });

        BArtefactos1.setBackground(new java.awt.Color(204, 204, 204));
        BArtefactos1.setForeground(new java.awt.Color(0, 0, 0));
        BArtefactos1.setText("Mis Artefactos");
        BArtefactos1.setBackgroundHover(new java.awt.Color(255, 102, 0));
        BArtefactos1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BArtefactos1.setForegroundIconHover(new java.awt.Color(51, 51, 51));
        BArtefactos1.setForegroundText(new java.awt.Color(51, 51, 51));
        BArtefactos1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.TV);
        BArtefactos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BArtefactos1ActionPerformed(evt);
            }
        });

        BAjustes.setBackground(new java.awt.Color(204, 204, 204));
        BAjustes.setForeground(new java.awt.Color(0, 0, 0));
        BAjustes.setText("Ajustes");
        BAjustes.setBackgroundHover(new java.awt.Color(255, 102, 0));
        BAjustes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BAjustes.setForegroundIconHover(new java.awt.Color(51, 51, 51));
        BAjustes.setForegroundText(new java.awt.Color(51, 51, 51));
        BAjustes.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SETTINGS);
        BAjustes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAjustesActionPerformed(evt);
            }
        });

        BFacturas.setBackground(new java.awt.Color(204, 204, 204));
        BFacturas.setForeground(new java.awt.Color(0, 0, 0));
        BFacturas.setText("Facturas");
        BFacturas.setBackgroundHover(new java.awt.Color(255, 102, 0));
        BFacturas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BFacturas.setForegroundIconHover(new java.awt.Color(51, 51, 51));
        BFacturas.setForegroundText(new java.awt.Color(51, 51, 51));
        BFacturas.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SHOP_TWO);
        BFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFacturasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rSPanelMaterial2Layout = new javax.swing.GroupLayout(rSPanelMaterial2);
        rSPanelMaterial2.setLayout(rSPanelMaterial2Layout);
        rSPanelMaterial2Layout.setHorizontalGroup(
            rSPanelMaterial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelMaterial2Layout.createSequentialGroup()
                .addGroup(rSPanelMaterial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JNombreU, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                    .addComponent(BEstadistica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BArtefactos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BAjustes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BFacturas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(rSPanelMaterial2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(rSPanelBorderImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rSPanelMaterial2Layout.setVerticalGroup(
            rSPanelMaterial2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelMaterial2Layout.createSequentialGroup()
                .addComponent(rSPanelBorderImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JNombreU, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BArtefactos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BEstadistica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BFacturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(BAjustes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jScrollPane1.setBorder(null);

        pnlSlider.setBackground(new java.awt.Color(255, 255, 255));
        pnlSlider.setLayout(new javax.swing.BoxLayout(pnlSlider, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPane1.setViewportView(pnlSlider);

        javax.swing.GroupLayout pnlCentroLayout = new javax.swing.GroupLayout(pnlCentro);
        pnlCentro.setLayout(pnlCentroLayout);
        pnlCentroLayout.setHorizontalGroup(
            pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelMaterial1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlCentroLayout.createSequentialGroup()
                .addComponent(rSPanelMaterial2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        pnlCentroLayout.setVerticalGroup(
            pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCentroLayout.createSequentialGroup()
                .addComponent(rSPanelMaterial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rSPanelMaterial2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCentro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCentro, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BInicioActionPerformed
        // TODO add your handling code here:
        if (!this.BInicio.isSelected()) {
            this.BInicio.setSelected(true);
            this.BArtefactos1.setSelected(false);
            this.BEstadistica.setSelected(false);
            this.BAjustes.setSelected(false);
            this.BFacturas.setSelected(false);
        }
        new CambiarPanel(pnlSlider, new paneles.inicio());
    }//GEN-LAST:event_BInicioActionPerformed

    private void BEstadisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEstadisticaActionPerformed
        // TODO add your handling code here:
        if (!this.BEstadistica.isSelected()) {
            this.BInicio.setSelected(false);
            this.BArtefactos1.setSelected(false);
            this.BEstadistica.setSelected(true);
            this.BAjustes.setSelected(false);
            this.BFacturas.setSelected(false);
        }
        new CambiarPanel(pnlSlider, new paneles.pnlEstadistica());

    }//GEN-LAST:event_BEstadisticaActionPerformed

    private void BArtefactos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BArtefactos1ActionPerformed
        // TODO add your handling code here:
        if (!this.BArtefactos1.isSelected()) {
            this.BInicio.setSelected(false);
            this.BArtefactos1.setSelected(true);
            this.BEstadistica.setSelected(false);
            this.BAjustes.setSelected(false);
            this.BFacturas.setSelected(false);
        }
        new CambiarPanel(pnlSlider, new paneles.pnlArtefactos());
    }//GEN-LAST:event_BArtefactos1ActionPerformed

    private void rSButtonIconTwo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconTwo1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new inicio_sesion().setVisible(true);
    }//GEN-LAST:event_rSButtonIconTwo1ActionPerformed

    private void BAjustesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAjustesActionPerformed
        // TODO add your handling code here:
        if (!this.BAjustes.isSelected()) {
            this.BInicio.setSelected(false);
            this.BArtefactos1.setSelected(false);
            this.BEstadistica.setSelected(false);
            this.BAjustes.setSelected(true);
            this.BFacturas.setSelected(false);
        }
        new CambiarPanel(pnlSlider, new paneles.pnlAjustes());
    }//GEN-LAST:event_BAjustesActionPerformed

    private void BFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFacturasActionPerformed
        // TODO add your handling code here:
        if (!this.BFacturas.isSelected()) {
            this.BInicio.setSelected(false);
            this.BArtefactos1.setSelected(false);
            this.BEstadistica.setSelected(false);
            this.BAjustes.setSelected(false);
            this.BFacturas.setSelected(true);
        }
        new CambiarPanel(pnlSlider, new paneles.pnlFacturas());
    }//GEN-LAST:event_BFacturasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicioU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicioU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicioU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicioU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicioU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialIconOne BAjustes;
    private RSMaterialComponent.RSButtonMaterialIconOne BArtefactos1;
    private RSMaterialComponent.RSButtonMaterialIconOne BEstadistica;
    private RSMaterialComponent.RSButtonMaterialIconOne BFacturas;
    private RSMaterialComponent.RSButtonMaterialIconOne BInicio;
    private javax.swing.JLabel JNombreU;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlSlider;
    private RSMaterialComponent.RSButtonIconTwo rSButtonIconTwo1;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon1;
    private RSMaterialComponent.RSPanelBorderImage rSPanelBorderImage1;
    private RSMaterialComponent.RSPanelMaterial rSPanelMaterial1;
    private RSMaterialComponent.RSPanelMaterial rSPanelMaterial2;
    // End of variables declaration//GEN-END:variables
}
