/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;
import RSMaterialComponent.RSPanelMaterialGradient;
import java.sql.*;
import gastoelectrico.Conexion;
import java.awt.Color;
import javax.swing.JOptionPane;
import ventanas.inicio_sesion;
/**
 *
 * @author Red
 */
public class inicio extends javax.swing.JPanel {
    String user="";
    

    /**
     * Creates new form inicio
     */
    public inicio() {
        initComponents();
        user = inicio_sesion.user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new RSMaterialComponent.RSPanelBorderGradient();
        rSLabelIcon1 = new RSMaterialComponent.RSLabelIcon();
        jLabel1 = new javax.swing.JLabel();
        contador = new javax.swing.JLabel();
        panel2 = new RSMaterialComponent.RSPanelBorderGradient();
        indicador = new rojerusan.componentes.RSProgressCircle();
        rSPanelMaterialGradient1 = new RSMaterialComponent.RSPanelMaterialGradient();
        cbMes = new newscomponents.RSDateMonth();
        BConsultar = new RSMaterialComponent.RSButtonMaterialIconOne();
        rSLabelTextIcon1 = new RSMaterialComponent.RSLabelTextIcon();

        setBackground(new java.awt.Color(0, 102, 102));

        rSLabelIcon1.setForeground(new java.awt.Color(255, 255, 255));
        rSLabelIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DESCRIPTION);
        rSLabelIcon1.setSizeIcon(60.0F);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Artefactos Registrados");

        contador.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        contador.setForeground(new java.awt.Color(255, 255, 255));
        contador.setText("0");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSLabelIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(contador))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSLabelIcon1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contador)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        indicador.setBackground(new java.awt.Color(255, 255, 255));
        indicador.setForeground(new java.awt.Color(255, 255, 255));
        indicador.setValue(100);
        indicador.setColorText(new java.awt.Color(255, 255, 255));
        indicador.setName(""); // NOI18N
        indicador.setPreferredSize(new java.awt.Dimension(147, 147));

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(indicador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(indicador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        rSPanelMaterialGradient1.setColorPrimario(new java.awt.Color(0, 0, 204));
        rSPanelMaterialGradient1.setColorSecundario(new java.awt.Color(0, 102, 102));

        cbMes.setColorArrow(new java.awt.Color(255, 255, 255));
        cbMes.setColorBoton(new java.awt.Color(0, 102, 102));
        cbMes.setColorFondo(new java.awt.Color(0, 37, 64));
        cbMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMesActionPerformed(evt);
            }
        });

        BConsultar.setBackground(new java.awt.Color(0, 153, 153));
        BConsultar.setText("Consultar");
        BConsultar.setBackgroundHover(new java.awt.Color(153, 0, 0));
        BConsultar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        BConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BConsultarActionPerformed(evt);
            }
        });

        rSLabelTextIcon1.setForeground(new java.awt.Color(255, 255, 255));
        rSLabelTextIcon1.setText("Indicador");
        rSLabelTextIcon1.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        rSLabelTextIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.MENU);

        javax.swing.GroupLayout rSPanelMaterialGradient1Layout = new javax.swing.GroupLayout(rSPanelMaterialGradient1);
        rSPanelMaterialGradient1.setLayout(rSPanelMaterialGradient1Layout);
        rSPanelMaterialGradient1Layout.setHorizontalGroup(
            rSPanelMaterialGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelMaterialGradient1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSLabelTextIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123)
                .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(BConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        rSPanelMaterialGradient1Layout.setVerticalGroup(
            rSPanelMaterialGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelMaterialGradient1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(rSPanelMaterialGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSLabelTextIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(rSPanelMaterialGradient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(rSPanelMaterialGradient1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMesActionPerformed

    private void BConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BConsultarActionPerformed
        // TODO add your handling code here:
        RSPanelMaterialGradient pg = new RSPanelMaterialGradient();
        String mes="";
        int c, porcentaje=0, numMes = cbMes.getSelectedIndex() + 1;
        int totalCarga=0;
        
        if(numMes == 1){
            mes = "Enero";
        }else if(numMes == 2){
            mes = "Febrero";
        }else if(numMes == 3){
            mes = "Marzo";
        }else if(numMes == 4){
            mes = "Abril";
        }else if(numMes == 5){
            mes = "Mayo";
        }else if(numMes == 6){
            mes = "Junio";
        }else if(numMes == 7){
            mes = "Julio";
        }else if(numMes == 8){
            mes = "Agosto";
        }else if(numMes == 9){
            mes = "Septiembre";
        }else if(numMes == 10){
            mes = "Octubre";
        }else if(numMes == 11){
            mes = "Noviembre";
        }else if(numMes == 12){
            mes = "Diciembre";
        }

        try {
            Connection cn = Conexion.conectar();
            String sql = "SELECT COUNT(*), SUM(ROUND((carga*cantidad)*tiempo)), mes "
                    + "FROM artefacto NATURAL JOIN usuario WHERE arias = '" + user + "' AND mes = '" + mes + "'GROUP BY mes";
            PreparedStatement pst = cn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                c = rs.getInt("COUNT(*)");
                this.contador.setText(String.valueOf(c));
                totalCarga = rs.getInt("SUM(ROUND((carga*cantidad)*tiempo))");
            }
            
            if(totalCarga > 0){
                porcentaje = (totalCarga*100)/900;
            }
            
            this.indicador.setValue(porcentaje);
            
            cn.close();
            
            if(porcentaje < 50 && porcentaje >= 0){
                
                this.indicador.setForeground(Color.green);
            }else if(porcentaje > 50 && porcentaje < 60){
                
                this.indicador.setForeground(Color.yellow);
            }else{
                this.indicador.setForeground(Color.red);
            }
            
        } catch (SQLException e) {
            System.err.println("ERROR " + e);
            JOptionPane.showMessageDialog(null, "Error al consultar informacion");
        }
        
        
    }//GEN-LAST:event_BConsultarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialIconOne BConsultar;
    private newscomponents.RSDateMonth cbMes;
    private javax.swing.JLabel contador;
    private rojerusan.componentes.RSProgressCircle indicador;
    private javax.swing.JLabel jLabel1;
    private RSMaterialComponent.RSPanelBorderGradient panel1;
    private RSMaterialComponent.RSPanelBorderGradient panel2;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon1;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon1;
    private RSMaterialComponent.RSPanelMaterialGradient rSPanelMaterialGradient1;
    // End of variables declaration//GEN-END:variables
}
