/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import helpers.RSButtonsAction;
import helpers.RSButtonsRenderer;
import gastoelectrico.Conexion;
import helpers.StyleHeadTable;
import java.awt.Color;
import java.awt.Font;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import ventanas.inicio_sesion;


/**
 *
 * @author Red
 */
public class pnlArtefactos extends javax.swing.JPanel {

    public static int id_artefacto;

    String user;
    private static StyleHeadTable headTable = new StyleHeadTable();

    /**
     * Creates new form prueba
     */
    public pnlArtefactos() {
        initComponents();
        user = inicio_sesion.user;
        DefaultTableModel model = (DefaultTableModel) JTable_artefactos.getModel();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        try {

            String sql = "SELECT nombreArt, carga, cantidad, tiempo, mes,ROUND(((carga*cantidad)*tiempo)*valor), id_artefacto FROM artefacto NATURAL JOIN usuario NATURAL JOIN estrato WHERE arias = '" + user + "'";
            
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(sql);

            ResultSet rs = pst.executeQuery();

            JTable_artefactos.setModel(model);
            

            while (rs.next()) {
                Object[] fila = new Object[7];
                for(int i=0; i<7; i++){
                     fila[i] = rs.getObject(i + 1);
                }
                model.addRow(fila);
            }
            cn.close();

        } catch (SQLException e) {
            System.err.println("Error" + e);
            JOptionPane.showMessageDialog(null, "Error al mostrar información");
        }

        TableColumn column = JTable_artefactos.getColumnModel().getColumn(7);
        column.setCellRenderer(new RSButtonsRenderer());
        String metodoVer = "viewinfo";
        String metodoEditar = "editinfo";
        String className = "paneles.pnlArtefactos";
        Object[] params = {className, metodoVer, metodoEditar};
        column.setCellEditor(new RSButtonsAction(JTable_artefactos, 6, params));
        
        //Renderizar Head Table
        headTable.backgoundHead = Color.RED;
        headTable.roregroundHead = Color.WHITE;
        headTable.fontHead = new Font("Tahoma", Font.BOLD, 14);
        headTable.hightHead = 45;
        JTable_artefactos.getTableHeader().setDefaultRenderer(headTable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        rSLabelTextIcon4 = new RSMaterialComponent.RSLabelTextIcon();
        BRegistrarA = new RSMaterialComponent.RSButtonMaterialIconOne();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTable_artefactos = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 0, new java.awt.Color(153, 153, 153)));

        rSLabelTextIcon4.setForeground(new java.awt.Color(204, 51, 0));
        rSLabelTextIcon4.setText("Mis Artefactos");
        rSLabelTextIcon4.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        rSLabelTextIcon4.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.TV);

        BRegistrarA.setBackground(new java.awt.Color(51, 255, 51));
        BRegistrarA.setText("Agregar artefacto");
        BRegistrarA.setBackgroundHover(new java.awt.Color(51, 255, 51));
        BRegistrarA.setFont(new java.awt.Font("Roboto Bold", 3, 14)); // NOI18N
        BRegistrarA.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD);
        BRegistrarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRegistrarAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSLabelTextIcon4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BRegistrarA, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSLabelTextIcon4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BRegistrarA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        JTable_artefactos.setAutoCreateRowSorter(true);
        JTable_artefactos.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        JTable_artefactos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Carga(KW)", "Cantidad", "Tiempo", "Mes", "Valor", "ID", "Acción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTable_artefactos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JTable_artefactos.setGridColor(new java.awt.Color(0, 0, 0));
        JTable_artefactos.setRowHeight(40);
        JTable_artefactos.setShowGrid(true);
        JTable_artefactos.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(JTable_artefactos);
        if (JTable_artefactos.getColumnModel().getColumnCount() > 0) {
            JTable_artefactos.getColumnModel().getColumn(4).setPreferredWidth(100);
            JTable_artefactos.getColumnModel().getColumn(4).setMaxWidth(100);
            JTable_artefactos.getColumnModel().getColumn(6).setMinWidth(0);
            JTable_artefactos.getColumnModel().getColumn(6).setPreferredWidth(0);
            JTable_artefactos.getColumnModel().getColumn(6).setMaxWidth(0);
            JTable_artefactos.getColumnModel().getColumn(7).setPreferredWidth(95);
            JTable_artefactos.getColumnModel().getColumn(7).setMaxWidth(95);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BRegistrarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRegistrarAActionPerformed
        // TODO add your handling code here:
       
        new ventanas.registrarA().setVisible(true);

    }//GEN-LAST:event_BRegistrarAActionPerformed

    public void editinfo(Object value) {
        //JOptionPane.showMessageDialog(null, "Edit"+value);
        id_artefacto = (Integer)value;
        new ventanas.actualizarA().setVisible(true);
        

    }

    public void viewinfo(Object value) {
        id_artefacto = (Integer)value;
        new ventanas.eliminarA().setVisible(true);
        

    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialIconOne BRegistrarA;
    private javax.swing.JTable JTable_artefactos;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon4;
    // End of variables declaration//GEN-END:variables
}
