/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import gastoelectrico.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.WindowConstants;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import ventanas.inicio_sesion;

/**
 *
 * @author Red
 */
public class pnlEstadistica extends javax.swing.JPanel {

    /**
     * Creates new form pnlEstadistica
     */
    public pnlEstadistica() {
        initComponents();
        this.BGrafico1.setSelected(true);
        new CambiarPanel(pnlSliderE, new paneles.pnlGrafico1());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGrafico5 = new RSMaterialComponent.RSButtonMaterialTwo();
        jPanel4 = new javax.swing.JPanel();
        BGrafico1 = new RSMaterialComponent.RSButtonMaterialTwo();
        BGrafico2 = new RSMaterialComponent.RSButtonMaterialTwo();
        BGrafico3 = new RSMaterialComponent.RSButtonMaterialTwo();
        BGrafico4 = new RSMaterialComponent.RSButtonMaterialTwo();
        pnlSliderE = new newscomponents.RSPanelEffect();

        BGrafico5.setBackground(new java.awt.Color(0, 102, 102));
        BGrafico5.setText("Factura mensual");
        BGrafico5.setBackgroundHover(new java.awt.Color(255, 51, 0));

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 0, new java.awt.Color(153, 153, 153)));

        BGrafico1.setBackground(new java.awt.Color(0, 102, 102));
        BGrafico1.setText("Al año");
        BGrafico1.setBackgroundHover(new java.awt.Color(255, 51, 0));
        BGrafico1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGrafico1ActionPerformed(evt);
            }
        });

        BGrafico2.setBackground(new java.awt.Color(0, 102, 102));
        BGrafico2.setText("Al mes");
        BGrafico2.setBackgroundHover(new java.awt.Color(255, 51, 0));
        BGrafico2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGrafico2ActionPerformed(evt);
            }
        });

        BGrafico3.setBackground(new java.awt.Color(0, 102, 102));
        BGrafico3.setText("Factura anual");
        BGrafico3.setBackgroundHover(new java.awt.Color(255, 51, 0));
        BGrafico3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGrafico3ActionPerformed(evt);
            }
        });

        BGrafico4.setBackground(new java.awt.Color(0, 102, 102));
        BGrafico4.setText("Factura mensual");
        BGrafico4.setBackgroundHover(new java.awt.Color(255, 51, 0));
        BGrafico4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGrafico4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(BGrafico1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BGrafico2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BGrafico3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BGrafico4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 182, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BGrafico1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BGrafico2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BGrafico3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BGrafico4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pnlSliderE.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlSliderE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSliderE, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BGrafico1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGrafico1ActionPerformed
        // TODO add your handling code here:
        new CambiarPanel(pnlSliderE, new pnlGrafico1());
        if (!this.BGrafico1.isSelected()) {
            this.BGrafico1.setSelected(true);
            this.BGrafico2.setSelected(false);
            this.BGrafico3.setSelected(false);
            this.BGrafico3.setSelected(false);
        }

    }//GEN-LAST:event_BGrafico1ActionPerformed

    private void BGrafico2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGrafico2ActionPerformed
        // TODO add your handling code here:
        new CambiarPanel(pnlSliderE, new pnlGrafico2());
        if (!this.BGrafico2.isSelected()) {
            this.BGrafico1.setSelected(false);
            this.BGrafico2.setSelected(true);
            this.BGrafico3.setSelected(false);
            this.BGrafico3.setSelected(false);
        }
    }//GEN-LAST:event_BGrafico2ActionPerformed

    private void BGrafico3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGrafico3ActionPerformed
        // TODO add your handling code here:
        new CambiarPanel(pnlSliderE, new pnlGrafico3());
        if (!this.BGrafico3.isSelected()) {
            this.BGrafico1.setSelected(false);
            this.BGrafico2.setSelected(false);
            this.BGrafico3.setSelected(true);
            this.BGrafico3.setSelected(false);
        }
    }//GEN-LAST:event_BGrafico3ActionPerformed

    private void BGrafico4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGrafico4ActionPerformed
        // TODO add your handling code here:
        new CambiarPanel(pnlSliderE, new pnlGrafico4());
        if (!this.BGrafico4.isSelected()) {
            this.BGrafico1.setSelected(false);
            this.BGrafico2.setSelected(false);
            this.BGrafico3.setSelected(false);
            this.BGrafico3.setSelected(true);
        }
    }//GEN-LAST:event_BGrafico4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialTwo BGrafico1;
    private RSMaterialComponent.RSButtonMaterialTwo BGrafico2;
    private RSMaterialComponent.RSButtonMaterialTwo BGrafico3;
    private RSMaterialComponent.RSButtonMaterialTwo BGrafico4;
    private RSMaterialComponent.RSButtonMaterialTwo BGrafico5;
    private javax.swing.JPanel jPanel4;
    private newscomponents.RSPanelEffect pnlSliderE;
    // End of variables declaration//GEN-END:variables
}
