/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;
import java.sql.*;
import ventanas.inicio_sesion;
import gastoelectrico.Conexion;
import javax.swing.JOptionPane;
/**
 *
 * @author Red
 */
public class pnlFactura2 extends javax.swing.JPanel {

    String user = "",m;
    int carga,valor,estrato;
    /**
     * Creates new form pnlFactura1
     */
    public pnlFactura2() {
        initComponents();
        user = inicio_sesion.user;
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelMaterial1 = new RSMaterialComponent.RSPanelMaterial();
        rSLabelTextIcon3 = new RSMaterialComponent.RSLabelTextIcon();
        jLabel3 = new javax.swing.JLabel();
        txtValor = new javax.swing.JLabel();
        rSLabelTextIcon4 = new RSMaterialComponent.RSLabelTextIcon();
        txtCarga1 = new javax.swing.JLabel();
        txtInfo = new javax.swing.JLabel();
        rSLabelTextIcon2 = new RSMaterialComponent.RSLabelTextIcon();
        jLabel2 = new javax.swing.JLabel();
        txtCarga = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMes = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtEstrato = new javax.swing.JLabel();
        cbMes = new newscomponents.RSDateMonth();
        BConsultar = new RSMaterialComponent.RSButtonMaterialIconOne();

        rSPanelMaterial1.setBackground(new java.awt.Color(255, 255, 255));

        rSLabelTextIcon3.setForeground(new java.awt.Color(0, 0, 0));
        rSLabelTextIcon3.setText("Valor :");
        rSLabelTextIcon3.setFont(new java.awt.Font("Roboto Bold", 1, 15)); // NOI18N
        rSLabelTextIcon3.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.INFO);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("2020");

        txtValor.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtValor.setText("0 KW");

        rSLabelTextIcon4.setForeground(new java.awt.Color(0, 0, 0));
        rSLabelTextIcon4.setText("Empresa :");
        rSLabelTextIcon4.setFont(new java.awt.Font("Roboto Bold", 1, 15)); // NOI18N
        rSLabelTextIcon4.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.BUSINESS_CENTER);

        txtCarga1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtCarga1.setText("Codensa");

        txtInfo.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtInfo.setText("Información General");

        rSLabelTextIcon2.setForeground(new java.awt.Color(0, 0, 0));
        rSLabelTextIcon2.setText("Carga KW/H :");
        rSLabelTextIcon2.setFont(new java.awt.Font("Roboto Bold", 1, 15)); // NOI18N
        rSLabelTextIcon2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.POWER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel2.setText("Año :");

        txtCarga.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtCarga.setText("$0");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel4.setText("Mes :");

        txtMes.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtMes.setText("Unknown");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel5.setText("Estrato: ");

        txtEstrato.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtEstrato.setText("0");

        javax.swing.GroupLayout rSPanelMaterial1Layout = new javax.swing.GroupLayout(rSPanelMaterial1);
        rSPanelMaterial1.setLayout(rSPanelMaterial1Layout);
        rSPanelMaterial1Layout.setHorizontalGroup(
            rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtInfo)
                        .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                            .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(rSLabelTextIcon4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCarga1)
                                .addComponent(txtMes)))
                        .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                            .addComponent(rSLabelTextIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCarga))
                        .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                            .addComponent(rSLabelTextIcon3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtValor)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelMaterial1Layout.createSequentialGroup()
                        .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2))
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEstrato)
                            .addComponent(jLabel3))
                        .addGap(63, 63, 63)))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        rSPanelMaterial1Layout.setVerticalGroup(
            rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(txtInfo)
                .addGap(18, 18, 18)
                .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMes))
                .addGap(4, 4, 4)
                .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSLabelTextIcon4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCarga1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSLabelTextIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCarga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSLabelTextIcon3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor))
                .addGap(5, 5, 5)
                .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEstrato))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(0, 21, Short.MAX_VALUE))
        );

        cbMes.setForeground(new java.awt.Color(0, 0, 0));
        cbMes.setColorArrow(new java.awt.Color(255, 0, 0));
        cbMes.setColorBorde(new java.awt.Color(255, 0, 0));
        cbMes.setColorBoton(new java.awt.Color(204, 204, 204));
        cbMes.setColorFondo(new java.awt.Color(255, 255, 255));
        cbMes.setColorSeleccion(new java.awt.Color(255, 51, 0));
        cbMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMesActionPerformed(evt);
            }
        });

        BConsultar.setBackground(new java.awt.Color(255, 0, 0));
        BConsultar.setText("Consultar");
        BConsultar.setBackgroundHover(new java.awt.Color(153, 0, 0));
        BConsultar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        BConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rSPanelMaterial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(rSPanelMaterial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMesActionPerformed

    private void BConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BConsultarActionPerformed
        // TODO add your handling code here:
        int numMes = cbMes.getSelectedIndex() + 1;
        String mes="";

        if(numMes == 1){
            mes = "Enero";
        }else if(numMes == 2){
            mes = "Febrero";
        }else if(numMes == 3){
            mes = "Marzo";
        }else if(numMes == 4){
            mes = "Abril";
        }else if(numMes == 5){
            mes = "Mayo";
        }else if(numMes == 6){
            mes = "Junio";
        }else if(numMes == 7){
            mes = "Julio";
        }else if(numMes == 8){
            mes = "Agosto";
        }else if(numMes == 9){
            mes = "Septiembre";
        }else if(numMes == 10){
            mes = "Octubre";
        }else if(numMes == 11){
            mes = "Noviembre";
        }else if(numMes == 12){
            mes = "Diciembre";
        }

         try {
            Connection cn = Conexion.conectar();
            String sql = "SELECT mes, SUM((carga*cantidad)*tiempo), SUM(ROUND((carga*cantidad)*tiempo)*valor), id_estrato "
                    + "FROM artefacto NATURAL JOIN usuario NATURAL JOIN estrato WHERE arias = '" + user + "' AND mes = '" + mes + "'";
            PreparedStatement pst = cn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
                carga = rs.getInt("SUM((carga*cantidad)*tiempo)");
                txtCarga.setText(String.valueOf(carga)+" KW");
                valor = rs.getInt("SUM(ROUND((carga*cantidad)*tiempo)*valor)");
                txtValor.setText("$"+String.valueOf(valor));
                m = rs.getString("mes");
                txtMes.setText(m);
                estrato = rs.getInt("id_estrato");
                txtEstrato.setText(String.valueOf(estrato));
            }
            
            cn.close();
            
        } catch (SQLException e) {
            System.err.println("Error " + e);
            JOptionPane.showMessageDialog(null, "Error al consultar informacion en la base de datos");
        }
    }//GEN-LAST:event_BConsultarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialIconOne BConsultar;
    private newscomponents.RSDateMonth cbMes;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon2;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon3;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon4;
    private RSMaterialComponent.RSPanelMaterial rSPanelMaterial1;
    private javax.swing.JLabel txtCarga;
    private javax.swing.JLabel txtCarga1;
    private javax.swing.JLabel txtEstrato;
    private javax.swing.JLabel txtInfo;
    private javax.swing.JLabel txtMes;
    private javax.swing.JLabel txtValor;
    // End of variables declaration//GEN-END:variables
}
