/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

/**
 *
 * @author Red
 */
public class pnlFacturas extends javax.swing.JPanel {

    /**
     * Creates new form pnlFacturas
     */
    public pnlFacturas() {
        initComponents();
        this.BFacAnual.setSelected(true);
        new CambiarPanel(pnlSliderF, new pnlFactura1());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelBorderGradient1 = new RSMaterialComponent.RSPanelBorderGradient();
        rSLabelTextIcon1 = new RSMaterialComponent.RSLabelTextIcon();
        BFacAnual = new RSMaterialComponent.RSButtonMaterialOne();
        BFacMes = new RSMaterialComponent.RSButtonMaterialOne();
        pnlSliderF = new newscomponents.RSPanelEffect();

        rSPanelBorderGradient1.setBgShade(new java.awt.Color(51, 51, 51));
        rSPanelBorderGradient1.setBorderLeft(false);
        rSPanelBorderGradient1.setBorderRight(false);
        rSPanelBorderGradient1.setBorderTop(false);
        rSPanelBorderGradient1.setColorPrimario(new java.awt.Color(255, 0, 0));
        rSPanelBorderGradient1.setColorSecundario(new java.awt.Color(102, 0, 0));

        rSLabelTextIcon1.setForeground(new java.awt.Color(255, 255, 255));
        rSLabelTextIcon1.setText("Ver Facturas");
        rSLabelTextIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SHOP_TWO);
        rSLabelTextIcon1.setSizeIcon(30.0F);

        BFacAnual.setBackground(new java.awt.Color(153, 0, 0));
        BFacAnual.setText("Anual");
        BFacAnual.setBackgroundHover(new java.awt.Color(255, 102, 0));
        BFacAnual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFacAnualActionPerformed(evt);
            }
        });

        BFacMes.setBackground(new java.awt.Color(153, 0, 0));
        BFacMes.setText("Al mes");
        BFacMes.setBackgroundHover(new java.awt.Color(255, 102, 0));
        BFacMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFacMesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rSPanelBorderGradient1Layout = new javax.swing.GroupLayout(rSPanelBorderGradient1);
        rSPanelBorderGradient1.setLayout(rSPanelBorderGradient1Layout);
        rSPanelBorderGradient1Layout.setHorizontalGroup(
            rSPanelBorderGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelBorderGradient1Layout.createSequentialGroup()
                .addComponent(rSLabelTextIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(rSPanelBorderGradient1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BFacAnual, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BFacMes, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(467, Short.MAX_VALUE))
        );
        rSPanelBorderGradient1Layout.setVerticalGroup(
            rSPanelBorderGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelBorderGradient1Layout.createSequentialGroup()
                .addComponent(rSLabelTextIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(rSPanelBorderGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BFacAnual, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BFacMes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlSliderF.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelBorderGradient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlSliderF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(rSPanelBorderGradient1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSliderF, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BFacAnualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFacAnualActionPerformed
        // TODO add your handling code here:
        new CambiarPanel(pnlSliderF, new pnlFactura1());
        if(this.BFacAnual.isSelected()){
            this.BFacAnual.setSelected(true);
            this.BFacMes.setSelected(false);
        }
    }//GEN-LAST:event_BFacAnualActionPerformed

    private void BFacMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFacMesActionPerformed
        // TODO add your handling code here:
        new CambiarPanel(pnlSliderF, new pnlFactura2());
        if(this.BFacAnual.isSelected()){
            this.BFacAnual.setSelected(false);
            this.BFacMes.setSelected(true);
        }
    }//GEN-LAST:event_BFacMesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialOne BFacAnual;
    private RSMaterialComponent.RSButtonMaterialOne BFacMes;
    private newscomponents.RSPanelEffect pnlSliderF;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon1;
    private RSMaterialComponent.RSPanelBorderGradient rSPanelBorderGradient1;
    // End of variables declaration//GEN-END:variables
}
