/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;
import java.sql.*;
import ventanas.inicio_sesion;
import gastoelectrico.Conexion;
import javax.swing.JOptionPane;
/**
 *
 * @author Red
 */
public class pnlFactura1 extends javax.swing.JPanel {

    String user = "";
    int carga,valor,estrato;
    /**
     * Creates new form pnlFactura1
     */
    public pnlFactura1() {
        initComponents();
        user = inicio_sesion.user;
        try {
            Connection cn = Conexion.conectar();
            String sql = "SELECT SUM((carga*cantidad)*tiempo), SUM(ROUND((carga*cantidad)*tiempo)*valor), id_estrato "
                    + "FROM artefacto NATURAL JOIN usuario NATURAL JOIN estrato WHERE arias = '" + user + "'";
            PreparedStatement pst = cn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
                carga = rs.getInt("SUM((carga*cantidad)*tiempo)");
                txtCarga.setText(String.valueOf(carga)+" KW");
                valor = rs.getInt("SUM(ROUND((carga*cantidad)*tiempo)*valor)");
                txtValor.setText("$"+String.valueOf(valor));
                estrato = rs.getInt("id_estrato");
                txtEstrato.setText(String.valueOf(estrato));
            }
            
            cn.close();
            
        } catch (SQLException e) {
            System.err.println("Error " + e);
            JOptionPane.showMessageDialog(null, "Error al consultar informacion en la base de datos");
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelMaterial1 = new RSMaterialComponent.RSPanelMaterial();
        rSLabelTextIcon3 = new RSMaterialComponent.RSLabelTextIcon();
        jLabel3 = new javax.swing.JLabel();
        txtValor = new javax.swing.JLabel();
        rSLabelTextIcon4 = new RSMaterialComponent.RSLabelTextIcon();
        txtCarga1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rSLabelTextIcon2 = new RSMaterialComponent.RSLabelTextIcon();
        jLabel2 = new javax.swing.JLabel();
        txtCarga = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtEstrato = new javax.swing.JLabel();

        rSPanelMaterial1.setBackground(new java.awt.Color(255, 255, 255));

        rSLabelTextIcon3.setForeground(new java.awt.Color(0, 0, 0));
        rSLabelTextIcon3.setText("Valor :");
        rSLabelTextIcon3.setFont(new java.awt.Font("Roboto Bold", 1, 15)); // NOI18N
        rSLabelTextIcon3.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.INFO);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("2020");

        txtValor.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtValor.setText("jLabel2");

        rSLabelTextIcon4.setForeground(new java.awt.Color(0, 0, 0));
        rSLabelTextIcon4.setText("Empresa :");
        rSLabelTextIcon4.setFont(new java.awt.Font("Roboto Bold", 1, 15)); // NOI18N
        rSLabelTextIcon4.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.BUSINESS_CENTER);

        txtCarga1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtCarga1.setText("Codensa");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Información General");

        rSLabelTextIcon2.setForeground(new java.awt.Color(0, 0, 0));
        rSLabelTextIcon2.setText("Carga KW/H :");
        rSLabelTextIcon2.setFont(new java.awt.Font("Roboto Bold", 1, 15)); // NOI18N
        rSLabelTextIcon2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.POWER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel2.setText("Año :");

        txtCarga.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtCarga.setText("jLabel2");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel5.setText("Estrato: ");

        txtEstrato.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtEstrato.setText("0");

        javax.swing.GroupLayout rSPanelMaterial1Layout = new javax.swing.GroupLayout(rSPanelMaterial1);
        rSPanelMaterial1.setLayout(rSPanelMaterial1Layout);
        rSPanelMaterial1Layout.setHorizontalGroup(
            rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                                    .addGap(3, 3, 3)
                                    .addComponent(rSLabelTextIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCarga))
                                .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addComponent(rSLabelTextIcon3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtValor))
                                .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                                    .addComponent(rSLabelTextIcon4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCarga1)))))
                    .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEstrato))
                            .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)))))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        rSPanelMaterial1Layout.setVerticalGroup(
            rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelMaterial1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(58, 58, 58)
                .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCarga1)
                    .addComponent(rSLabelTextIcon4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSLabelTextIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCarga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSLabelTextIcon3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor))
                .addGap(4, 4, 4)
                .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEstrato))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(rSPanelMaterial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rSPanelMaterial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon2;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon3;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon4;
    private RSMaterialComponent.RSPanelMaterial rSPanelMaterial1;
    private javax.swing.JLabel txtCarga;
    private javax.swing.JLabel txtCarga1;
    private javax.swing.JLabel txtEstrato;
    private javax.swing.JLabel txtValor;
    // End of variables declaration//GEN-END:variables
}
