/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import gastoelectrico.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import ventanas.inicio_sesion;

/**
 *
 * @author Red
 */
public class pnlGrafico3 extends javax.swing.JPanel {
    String user = "";

    /**
     * Creates new form pnlGrafico1
     */
    public pnlGrafico3() {
        initComponents();
        user = inicio_sesion.user;
        try {
            Connection cn = Conexion.conectar();
            String sql = "SELECT mes, SUM(ROUND((carga*cantidad)*tiempo)*valor) FROM artefacto NATURAL JOIN usuario NATURAL JOIN estrato WHERE arias = '" + user + "' GROUP BY mes";
            PreparedStatement pst = cn.prepareStatement(sql);
            
            ResultSet rs = pst.executeQuery();
            
            DefaultCategoryDataset dtsc = new DefaultCategoryDataset();
            
            while(rs.next()){
                dtsc.setValue(Float.parseFloat(rs.getString(2)),"Total carga", rs.getString(1));
                JFreeChart ch = ChartFactory.createBarChart3D("HISTOGRAMA", "Mes", "Valor Total", dtsc, PlotOrientation.VERTICAL, true, true, false);
                ChartPanel cp = new ChartPanel(ch);
                add(cp);
                cp.setBounds(25, 15, 600, 400);
            }
            
        } catch (SQLException e) {
            System.err.println("Error" + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 354, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
