/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import gastoelectrico.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import ventanas.inicio_sesion;

/**
 *
 * @author Red
 */
public class pnlGrafico2 extends javax.swing.JPanel {
    String user="";

    /**
     * Creates new form pnlGrafico2
     */
    public pnlGrafico2() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbMes = new newscomponents.RSDateMonth();
        BMostrar = new RSMaterialComponent.RSButtonMaterialTwo();

        setBackground(new java.awt.Color(255, 255, 255));

        cbMes.setForeground(new java.awt.Color(0, 0, 0));
        cbMes.setColorArrow(new java.awt.Color(255, 0, 0));
        cbMes.setColorBorde(new java.awt.Color(255, 0, 0));
        cbMes.setColorBoton(new java.awt.Color(204, 204, 204));
        cbMes.setColorFondo(new java.awt.Color(255, 255, 255));
        cbMes.setColorSeleccion(new java.awt.Color(255, 51, 0));
        cbMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMesActionPerformed(evt);
            }
        });

        BMostrar.setBackground(new java.awt.Color(255, 0, 51));
        BMostrar.setText("Graficar");
        BMostrar.setBackgroundHover(new java.awt.Color(255, 51, 0));
        BMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(272, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 358, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMostrarActionPerformed

        removeAll();
        revalidate();
        repaint();
        String mes="";
        int numMes = cbMes.getSelectedIndex() + 1;
        

        if(numMes == 1){
            mes = "Enero";
        }else if(numMes == 2){
            mes = "Febrero";
        }else if(numMes == 3){
            mes = "Marzo";
        }else if(numMes == 4){
            mes = "Abril";
        }else if(numMes == 5){
            mes = "Mayo";
        }else if(numMes == 6){
            mes = "Junio";
        }else if(numMes == 7){
            mes = "Julio";
        }else if(numMes == 8){
            mes = "Agosto";
        }else if(numMes == 9){
            mes = "Septiembre";
        }else if(numMes == 10){
            mes = "Octubre";
        }else if(numMes == 11){
            mes = "Noviembre";
        }else if(numMes == 12){
            mes = "Diciembre";
        }

        user = inicio_sesion.user;
        try {
            Connection cn = Conexion.conectar();
            //String sql = "SELECT nombreArt, carga, cantidad, tiempo, mes FROM artefacto NATURAL JOIN usuario WHERE arias = '" + user + "'";
            String sql = "SELECT nombreArt, (carga * cantidad)*tiempo FROM artefacto NATURAL JOIN usuario WHERE arias = '" + user + "' AND mes = '" + mes + "'";
            PreparedStatement pst = cn.prepareStatement(sql);

            ResultSet rs = pst.executeQuery();

            DefaultCategoryDataset dtsc = new DefaultCategoryDataset();

            while(rs.next()){
                dtsc.setValue(Float.parseFloat(rs.getString(2)),"Total carga", rs.getString(1));
                JFreeChart ch = ChartFactory.createBarChart("", "Artefactos", "Carga", dtsc, PlotOrientation.HORIZONTAL, true, false, false);
                ChartPanel cp = new ChartPanel(ch);
                add(cp);
                cp.setBounds(25, 15, 600, 400);
            }
            
            

        } catch (SQLException e) {
            System.err.println("Error" + e);
        }

    }//GEN-LAST:event_BMostrarActionPerformed

    private void cbMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialTwo BMostrar;
    private newscomponents.RSDateMonth cbMes;
    // End of variables declaration//GEN-END:variables
}
