/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import helpers.RSButtonsAction;
import helpers.RSButtonsRenderer;
import gastoelectrico.Conexion;
import helpers.StyleHeadTable;
import java.awt.Color;
import java.awt.Font;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import ventanas.inicio_sesion;


/**
 *
 * @author Red
 */
public class pnlSolicitudes extends javax.swing.JPanel {

    public static int id_solicitud;

    String user;
    private static StyleHeadTable headTable = new StyleHeadTable();

    /**
     * Creates new form prueba
     */
    public pnlSolicitudes() {
        initComponents();
        user = inicio_sesion.user;
        DefaultTableModel model = (DefaultTableModel) JTable_solicitudes.getModel();

        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        try {

            String sql = "SELECT id_solicitud, id_user, arias, user_name, user_lastname, correo, telefono FROM usuario NATURAL JOIN solicitud";
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(sql);

            ResultSet rs = pst.executeQuery();

            JTable_solicitudes.setModel(model);
            

            while (rs.next()) {
                Object[] fila = new Object[7];
                for(int i=0; i<7; i++){
                     fila[i] = rs.getObject(i + 1);
                }
                model.addRow(fila);
            }
            cn.close();

        } catch (SQLException e) {
            System.err.println("Error" + e);
            JOptionPane.showMessageDialog(null, "Error al mostrar información");
        }

        TableColumn column = JTable_solicitudes.getColumnModel().getColumn(7);
        column.setCellRenderer(new RSButtonsRenderer());
        String metodoVer = "viewinfo";
        String metodoEditar = "editinfo";
        String className = "paneles.pnlSolicitudes";
        Object[] params = {className, metodoVer,metodoEditar};
        column.setCellEditor(new RSButtonsAction(JTable_solicitudes, 0, params));
        
        //Renderizar Head Table
        headTable.backgoundHead = new Color(0,204,204);
        headTable.roregroundHead = Color.WHITE;
        headTable.fontHead = new Font("Tahoma", Font.BOLD, 14);
        headTable.hightHead = 45;
        JTable_solicitudes.getTableHeader().setDefaultRenderer(headTable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        JTable_solicitudes = new javax.swing.JTable();
        rSPanelBorderGradient1 = new RSMaterialComponent.RSPanelBorderGradient();
        rSLabelTextIcon1 = new RSMaterialComponent.RSLabelTextIcon();

        setBackground(new java.awt.Color(255, 255, 255));

        JTable_solicitudes.setAutoCreateRowSorter(true);
        JTable_solicitudes.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        JTable_solicitudes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID solicitud", "ID user", "Nick", "Nombre", "Apellido", "Correo", "Teléfono", "Acción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTable_solicitudes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JTable_solicitudes.setGridColor(new java.awt.Color(0, 0, 0));
        JTable_solicitudes.setRowHeight(40);
        JTable_solicitudes.setShowGrid(true);
        JTable_solicitudes.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(JTable_solicitudes);
        if (JTable_solicitudes.getColumnModel().getColumnCount() > 0) {
            JTable_solicitudes.getColumnModel().getColumn(0).setMinWidth(0);
            JTable_solicitudes.getColumnModel().getColumn(0).setPreferredWidth(0);
            JTable_solicitudes.getColumnModel().getColumn(0).setMaxWidth(0);
            JTable_solicitudes.getColumnModel().getColumn(1).setMinWidth(0);
            JTable_solicitudes.getColumnModel().getColumn(1).setPreferredWidth(0);
            JTable_solicitudes.getColumnModel().getColumn(1).setMaxWidth(0);
            JTable_solicitudes.getColumnModel().getColumn(7).setPreferredWidth(100);
            JTable_solicitudes.getColumnModel().getColumn(7).setMaxWidth(100);
        }

        rSPanelBorderGradient1.setBgShade(new java.awt.Color(51, 51, 51));
        rSPanelBorderGradient1.setBorderLeft(false);
        rSPanelBorderGradient1.setBorderRight(false);
        rSPanelBorderGradient1.setBorderTop(false);
        rSPanelBorderGradient1.setColorPrimario(new java.awt.Color(0, 204, 204));

        rSLabelTextIcon1.setForeground(new java.awt.Color(255, 255, 255));
        rSLabelTextIcon1.setText("Solicitudes");
        rSLabelTextIcon1.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        rSLabelTextIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.VIEW_LIST);

        javax.swing.GroupLayout rSPanelBorderGradient1Layout = new javax.swing.GroupLayout(rSPanelBorderGradient1);
        rSPanelBorderGradient1.setLayout(rSPanelBorderGradient1Layout);
        rSPanelBorderGradient1Layout.setHorizontalGroup(
            rSPanelBorderGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelBorderGradient1Layout.createSequentialGroup()
                .addComponent(rSLabelTextIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        rSPanelBorderGradient1Layout.setVerticalGroup(
            rSPanelBorderGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelBorderGradient1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSLabelTextIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
            .addComponent(rSPanelBorderGradient1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(rSPanelBorderGradient1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void editinfo(Object value) {
        //JOptionPane.showMessageDialog(null, "Edit"+value);
        id_solicitud = (Integer)value;
        new ventanas.cambiarC2().setVisible(true);
        
    }

    public void viewinfo(Object value) {
        id_solicitud = (Integer)value;
        new ventanas.verSolicitud().setVisible(true);
        
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTable_solicitudes;
    private javax.swing.JScrollPane jScrollPane2;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon1;
    private RSMaterialComponent.RSPanelBorderGradient rSPanelBorderGradient1;
    // End of variables declaration//GEN-END:variables
}
